---
resources:
- name: grenade-deploy
  type: git
  source:
    uri: https://github.com/dolph/grenade-deploy.git
    branch: master
- name: devstack-lxc
  type: git
  source:
    uri: https://github.com/osic/devstack-lxc.git
    branch: master
- name: daily
  type: time
  source:
  - interval: 24h

jobs:
- name: grenade-master
  plan:
  - get: daily
    trigger: true
  - get: grenade-deploy
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: grenade-deploy
      run:
        path: grenade-deploy/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - master
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
- name: grenade-newton
  plan:
  - get: daily
    trigger: false
  - get: grenade-deploy
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: grenade-deploy
      run:
        path: grenade-deploy/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - stable/newton
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
- name: grenade-ocata
  plan:
  - get: daily
    trigger: false
  - get: grenade-deploy
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: grenade-deploy
      run:
        path: grenade-deploy/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - stable/ocata
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
- name: devstack
  serial: true
  plan:
  - get: daily
    trigger: true
  - get: grenade-deploy
    trigger: false
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: grenade-deploy
      run:
        path: grenade-deploy/ci/deploy-devstack.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
- name: devstack-lxc
  plan:
  - get: daily
    trigger: true
  - get: grenade-deploy
    trigger: true
  - get: devstack-lxc
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: grenade-deploy
      run:
        path: grenade-deploy/ci/deploy-devstack-lxc.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
