---
resources:
- name: pineapple
  type: git
  source:
    uri: https://github.com/dolph/pineapple.git
    branch: master
- name: devstack
  type: git
  source:
    uri: https://github.com/openstack-dev/devstack.git
    branch: master
- name: grenade
  type: git
  source:
    uri: https://github.com/openstack-dev/grenade.git
    branch: master
- name: devstack-lxc
  type: git
  source:
    uri: https://github.com/osic/devstack-lxc.git
    branch: multinode-vm-lxc
- name: osa-stable
  type: git
  source:
    uri: https://github.com/openstack/openstack-ansible.git
    branch: stable/newton
- name: osa-master
  type: git
  source:
    uri: https://github.com/openstack/openstack-ansible.git
    branch: master
- name: openstack-ansible-os_keystone
  type: git
  source:
    uri: https://github.com/openstack/openstack-ansible-os_keystone.git
    branch: master

jobs:
- name: smoke-test
  serial: false
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: pineapple
    trigger: true
  - task: test
    timeout: 15m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/smoke-test.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: devstack
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: devstack
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: devstack
      run:
        path: pineapple/ci/deploy-devstack.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        - ci-devstack
- name: grenade
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: grenade
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: grenade
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: devstack-lxc
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test, grenade]
    trigger: true
  - get: devstack-lxc
    trigger: true
  - get: grenade
    passed: [grenade]
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: devstack-lxc
      - name: grenade
      run:
        path: pineapple/ci/deploy-devstack-lxc.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: osa-stable
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: osa-stable
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: osa-stable
        path: openstack-ansible
      run:
        path: pineapple/ci/deploy-osa.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        - ci-osa-stable
- name: osa-master
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: osa-master
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: osa-master
        path: openstack-ansible
      run:
        path: pineapple/ci/deploy-osa.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        - ci-osa-master
- name: osa-upgrade
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test, osa-stable, osa-master]
    trigger: true
  - get: osa-stable
    passed: [osa-stable]
    trigger: true
  - get: osa-master
    passed: [osa-master]
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: osa-stable
      - name: osa-master
      run:
        path: pineapple/ci/upgrade-osa.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: os_keystone-upgrade
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: openstack-ansible-os_keystone
    trigger: true
  - task: deploy
    timeout: 1h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: openstack-ansible-os_keystone
      run:
        path: pineapple/ci/deploy-keystone.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
