---
resources:
- name: pineapple
  type: git
  source:
    uri: https://github.com/dolph/pineapple.git
    branch: master
- name: devstack-lxc
  type: git
  source:
    uri: https://github.com/osic/devstack-lxc.git
    branch: lxc-multinode-grenade
- name: daily
  type: time
  source:
  - interval: 24h

jobs:
- name: grenade-master-16.04
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: daily
    trigger: true
  - get: pineapple
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - master
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: grenade-master-14.04
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: daily
    trigger: true
  - get: pineapple
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - master
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
- name: grenade-newton
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: daily
    trigger: false
  - get: pineapple
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - stable/newton
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: grenade-ocata
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: daily
    trigger: false
  - get: pineapple
    trigger: false
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - stable/ocata
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: devstack-16.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: daily
    trigger: true
  - get: pineapple
    trigger: false
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-devstack.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        - ci-devstack-1604
- name: devstack-14.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: daily
    trigger: true
  - get: pineapple
    trigger: false
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-devstack.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        - ci-devstack-1404
- name: devstack-lxc-16.04
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: daily
    trigger: true
  - get: pineapple
    trigger: true
  - get: devstack-lxc
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-devstack-lxc.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: devstack-lxc-14.04
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: daily
    trigger: true
  - get: pineapple
    trigger: true
  - get: devstack-lxc
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/deploy-devstack-lxc.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
