---
resources:
- name: pineapple
  type: git
  source:
    uri: https://github.com/dolph/pineapple.git
    branch: master
- name: devstack
  type: git
  source:
    uri: https://github.com/openstack-dev/devstack.git
    branch: master
- name: grenade
  type: git
  source:
    uri: https://github.com/openstack-dev/grenade.git
    branch: master
- name: devstack-lxc
  type: git
  source:
    uri: https://github.com/osic/devstack-lxc.git
    branch: multinode-vm-lxc
- name: openstack-ansible
  type: git
  source:
    uri: https://github.com/openstack/openstack-ansible.git
    branch: stable-newton

jobs:
- name: smoke-test
  serial: false
  build_logs_to_retain: 3
  max_in_flight: 3
  plan:
  - get: pineapple
    trigger: true
  - task: test
    timeout: 15m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      run:
        path: pineapple/ci/smoke-test.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: devstack-16.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: devstack
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: devstack
      run:
        path: pineapple/ci/deploy-devstack.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        - ci-devstack-1604
- name: devstack-14.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: devstack
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: devstack
      run:
        path: pineapple/ci/deploy-devstack.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        - ci-devstack-1404
- name: grenade-16.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: grenade
    trigger: true
  - task: deploy
    timeout: 2h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: grenade
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: grenade-14.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: grenade
    trigger: true
  - task: deploy
    timeout: 2h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: grenade
      run:
        path: pineapple/ci/deploy-grenade.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
- name: devstack-lxc-16.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: devstack-lxc
    trigger: true
  - get: grenade
    passed: [grenade-16.04]
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: devstack-lxc
      - name: grenade
      run:
        path: pineapple/ci/deploy-devstack-lxc.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
- name: devstack-lxc-14.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: devstack-lxc
    trigger: true
  - get: grenade
    passed: [grenade-14.04]
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: devstack-lxc
      - name: grenade
      run:
        path: pineapple/ci/deploy-devstack-lxc.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
- name: osa-16.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: openstack-ansible
    trigger: true
  - task: deploy
    timeout: 2h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: openstack-ansible
      run:
        path: pineapple/ci/deploy-osa.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)
        - ci-osa-1604
- name: osa-14.04
  serial: true
  build_logs_to_retain: 3
  max_in_flight: 1
  plan:
  - get: pineapple
    passed: [smoke-test]
    trigger: true
  - get: openstack-ansible
    trigger: true
  - task: deploy
    timeout: 2h
    attempts: 1
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: pineapple
      - name: openstack-ansible
      run:
        path: pineapple/ci/deploy-osa.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
        - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
        - ci-osa-1404
