---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/grenade-deploy.git
    branch: master
- name: daily
  type: time
  source:
  - interval: 24h

jobs:
- name: master
  plan:
  - get: daily
    trigger: true
  - get: repo
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: repo
      run:
        path: repo/ci/deploy.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - master
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
- name: newton
  plan:
  - get: daily
    trigger: true
  - get: repo
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: repo
      run:
        path: repo/ci/deploy.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - stable/newton
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
- name: ocata
  plan:
  - get: daily
    trigger: true
  - get: repo
    trigger: true
  - task: deploy
    timeout: 3h
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: phusion/baseimage
      inputs:
      - name: repo
      run:
        path: repo/ci/deploy.sh
        args:
        - {{ssh_public_key}}
        - {{ssh_private_key_only}}
        - stable/ocata
        - {{rack_username}}
        - {{rack_api_key}}
        - {{rack_region}}
